[target]
name = step_ca
mode = pod

[network]
# ANPASSEN: Podman-Netzwerk und IP
network = podman
dns = 10.88.0.1
hostname = step-ca

[firewall]
ports = 9000

[pin]
step-ca = smallstep/step-ca:latest

[storage]
/home/step =
