[target]
name = step_ca
mode = pod

[network]
# ANPASSEN: Podman-Netzwerk und IP
network = CHANGE_ME:ip=CHANGE_ME
dns = CHANGE_ME
hostname = ca.nuhost6.local

[firewall]
ports = 9000

[pin]
step-ca = codeberg.org/kosmos-eu/openstep:latest

[storage]
/home/step =
