---
services:
  step-ca:
    image: ${STEP_CA_IMAGE:-codeberg.org/kosmos-eu/openstep}:${STEP_CA_TAG:-latest}
    container_name: step-ca
    restart: always
    environment:
      - CA_NAME=${CA_NAME:-nuhost6-ca}
      - CA_DNS=${CA_DNS:-step-ca,${STEP_CA_DOMAIN:-ca.localhost}}
      - CA_ADDRESS=:9000
      - CA_PASSWORD=${CA_PASSWORD:-}
      - ACME_PROVISIONER=${ACME_PROVISIONER:-acme}
    volumes:
      - step-ca-data:/home/step
    ports:
      - "${STEP_CA_PORT:-9000}:9000"
    logging:
      driver: ${LOG_DRIVER:-journald}

volumes:
  step-ca-data:
